REG_RESET = 0
REG_ECHO = 1
REG_SPEECH_LAST_WORD_OUT = 10
REG_SPEECH_BUF_COUNT = 11
REG_SPEECH_STATE = 12
REG_SPEECH_QUEUE_BANK = 13
REG_SPEECH_QUEUE_WORD = 14
REG_SPEECH_LAST_BANK_OUT = 15

SPEECH_INIT =             0x00
SPEECH_BUSY =             0x01
SPEECH_IDLE =             0x02
SPEECH_BUSYWAIT =         0x03
SPEECH_ACKED =            0x04
